2019-01-10 00:58:48,765 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 00:58:48,765 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 00:58:54,040 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 00:58:54,040 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 00:58:59,821 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 00:58:59,821 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 00:59:06,353 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 00:59:06,353 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:36:59,615 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:36:59,628 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:37:05,410 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:37:05,411 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:37:16,483 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:37:16,483 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:38:12,092 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:38:12,092 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:38:42,097 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:38:42,602 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:38:54,283 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2019-01-10 23:38:54,283 - __main__ - WARNING - Update "{'message': {'chat': {'all_members_are_administrators': True, 'id': -273384150, 'type': 'group', 'title': 'GitHub repoes'}, 'group_chat_created': False, 'date': 1547134711, 'from': {'username': 'inuwazz', 'id': 436384576, 'first_name': '¤j©M', 'language_code': 'zh-hans', 'is_bot': False}, 'new_chat_members': [], 'text': '/buy@DOMINION_IM_BOT', 'caption_entities': [], 'supergroup_chat_created': False, 'new_chat_photo': [], 'photo': [], 'channel_chat_created': False, 'message_id': 8744, 'delete_chat_photo': False, 'entities': [{'offset': 0, 'type': 'bot_command', 'length': 20}]}, 'update_id': 773023138}" caused error "Timed out"
2019-01-10 23:39:24,864 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:39:24,864 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:40:33,201 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:40:33,202 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:41:07,580 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:41:07,580 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:41:41,962 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:41:41,962 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:42:50,124 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:42:50,124 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:43:24,510 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:43:24,510 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:43:58,826 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:43:58,826 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:44:33,147 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:44:33,147 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:45:07,532 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:45:07,533 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:47:57,182 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:47:57,183 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:48:31,498 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:48:31,499 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:48:36,866 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:48:37,250 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:48:42,654 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:48:42,654 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:48:49,199 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:48:52,830 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2019-01-10 23:48:52,830 - __main__ - WARNING - Update "{'message': {'chat': {'all_members_are_administrators': True, 'id': -273384150, 'type': 'group', 'title': 'GitHub repoes'}, 'group_chat_created': False, 'date': 1547135310, 'from': {'username': 'Fukai_217', 'id': 337412327, 'first_name': 'Fukai', 'language_code': 'en', 'is_bot': False}, 'new_chat_members': [], 'text': '/buy@DOMINION_IM_BOT', 'caption_entities': [], 'supergroup_chat_created': False, 'new_chat_photo': [], 'photo': [], 'channel_chat_created': False, 'message_id': 8785, 'delete_chat_photo': False, 'entities': [{'offset': 0, 'type': 'bot_command', 'length': 20}]}, 'update_id': 773023154}" caused error "Timed out"
2019-01-10 23:48:52,830 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:48:56,867 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:49:00,012 - telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
2019-01-10 23:49:00,013 - __main__ - WARNING - Update "{'message': {'chat': {'all_members_are_administrators': True, 'id': -273384150, 'type': 'group', 'title': 'GitHub repoes'}, 'group_chat_created': False, 'date': 1547135316, 'from': {'username': 'inuwazz', 'id': 436384576, 'first_name': '¤j©M', 'language_code': 'zh-hans', 'is_bot': False}, 'new_chat_members': [], 'text': 'status', 'caption_entities': [], 'supergroup_chat_created': False, 'new_chat_photo': [], 'photo': [], 'channel_chat_created': False, 'message_id': 8786, 'delete_chat_photo': False, 'entities': []}, 'update_id': 773023155, '_effective_message': {'chat': {'all_members_are_administrators': True, 'id': -273384150, 'type': 'group', 'title': 'GitHub repoes'}, 'group_chat_created': False, 'date': 1547135316, 'from': {'username': 'inuwazz', 'id': 436384576, 'first_name': '¤j©M', 'language_code': 'zh-hans', 'is_bot': False}, 'new_chat_members': [], 'text': 'status', 'caption_entities': [], 'supergroup_chat_created': False, 'new_chat_photo': [], 'photo': [], 'channel_chat_created': False, 'message_id': 8786, 'delete_chat_photo': False, 'entities': []}}" caused error "Timed out"
2019-01-10 23:49:00,013 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:49:32,584 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:49:32,584 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:49:37,931 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:49:37,931 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:49:44,280 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:49:44,281 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:49:49,592 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:49:49,592 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:49:57,312 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:49:57,312 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:04,973 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:04,973 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:15,568 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:15,568 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:31,305 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:31,306 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:36,650 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:36,650 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:42,497 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:42,498 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:47,841 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:47,842 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:54,187 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:54,188 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:50:59,527 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:50:59,528 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:07,282 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:07,284 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:12,631 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:12,631 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:18,479 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:18,479 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:23,826 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:23,828 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:29,671 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:29,671 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:36,266 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:36,267 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:44,492 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:44,492 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:51:53,908 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:51:53,908 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:52:05,856 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:52:05,856 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:52:21,645 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:52:21,645 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:52:43,117 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:52:43,117 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:53:13,094 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:53:13,094 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:53:55,883 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:53:55,883 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:54:30,236 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:54:30,236 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:55:04,581 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:55:04,581 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:55:38,933 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:55:38,933 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:56:13,279 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:56:13,279 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:56:47,639 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:56:47,640 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:57:22,001 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:57:22,002 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
2019-01-10 23:57:56,354 - telegram.ext.updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)
2019-01-10 23:57:56,355 - __main__ - WARNING - Update "None" caused error "Conflict: terminated by other getUpdates request; make sure that only one bot instance is running (409)"
